name: Docker Build and Push
description: "Build Docker image and push to ACR"
inputs:
  acr-name:
    description: "Azure Container Registry name"
    required: true
  project-name:
    description: "Project name"
    required: true
  image-tag:
    description: "Versioned Docker image tag (e.g., 1.0.5)"
    required: true
  dockerfile-path:
    description: "Path to Dockerfile"
    required: false
    default: "./Dockerfile"
  context-path:
    description: "Docker build context path"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Docker Image
      working-directory: ${{ inputs.project-name }}
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context-path }}
        file: ${{ inputs.dockerfile-path }}
        push: true
        tags: |
          ${{ inputs.acr-name }}.azurecr.io/${{ inputs.project-name }}:latest
          ${{ inputs.acr-name }}.azurecr.io/${{ inputs.project-name }}:${{ inputs.image-tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max