name: Docker Login to ACR
description: "Login to Azure Container Registry"
inputs:
  acr-name:
    description: "Azure Container Registry name"
    required: true
  acr-username:
    description: "Azure Container Registry username"
    required: true
  acr-password:
    description: "Azure Container Registry password"
    required: true
runs:
  using: "composite"
  steps:
    - name: Login to ACR
      uses: azure/docker-login@v2
      with:
        login-server: ${{ inputs.acr-name }}.azurecr.io
        username: ${{ inputs.acr-username }}
        password: ${{ inputs.acr-password }}